additional_commands:
  database: "^database(\\(.+\\))?:"
  design: "^design(\\(.+\\))?:"
  security: "^security(\\(.+\\))?:"
  prompt: "^prompt(\\(.+\\))?:"
  merge: "^merge(\\(.+\\))?:"
  migration: "^migration(\\(.+\\))?:"


additional_emojis:
  database: " ğŸ—ƒï¸ "
  design: " ğŸ¨ "
  security: " ğŸ›¡ï¸ "
  merge: " â›“ï¸ "
  prompt: " ğŸ¤– "
  migration: " ğŸ” "
